name: wisatacandi
description: "aplikasi candi"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  encrypt: ^5.0.3
  logger: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - images/borobudur.jpeg
    - images/jago.jpeg
    - images/kalasan.jpeg
    - images/logo_candi.png
    - images/lumbung.jpeg
    - images/mendut.jpeg
    - images/placeholder_image.png
    - images/plaosan.jpeg
    - images/prambanan.jpeg
    - images/sari.jpeg
    - images/sewu.jpeg
    - images/singosari.jpeg